import csv
import json
from pathlib import Path
import os
import sys
from veriruntime.execution import ExecutionSpec, LocalExecutionBackend


def main():
    workspace = Path(sys.argv[1]).parent
    manifest = json.loads(Path(sys.argv[1]).read_text())
    run = LocalExecutionBackend().run_sync(ExecutionSpec(tuple(manifest['argv']), str(workspace),
        dict(os.environ)), inherit_group=True)
    (workspace / 'framac.stdout.log').write_text(run.stdout)
    (workspace / 'framac.stderr.log').write_text(run.stderr)
    report = workspace / 'properties.csv'
    rows = list(csv.DictReader(report.open(), delimiter='\t')) if report.exists() else []
    # Only the pinned standard assert model's frame is trusted without a body.
    # User ACSL is rejected by the adapter; all actual assertion call sites must
    # be proven Valid, never merely "Considered valid" or conditional.
    def valid(row):
        return row.get('status') == 'Valid' or (row.get('status') == 'Considered valid' and
            row.get('directory') == 'FRAMAC_SHARE/libc' and row.get('file') == 'assert.h' and
            row.get('function') == '__FC_assert' and row.get('property kind') == 'assigns clause')
    properties = [{'record': row, 'valid': valid(row)} for row in rows]
    has_assertion = any(row.get('property kind') == 'precondition of __FC_assert' for row in rows)
    complete = ('[eva:summary] ====== ANALYSIS SUMMARY ======' in run.stdout and
        'No errors or warnings raised during the analysis.' in run.stdout and
        '0 alarms generated by the analysis.' in run.stdout and not any(
        marker in run.stdout + run.stderr for marker in ('[kernel] User Error', '[eva] User Error', 'unsound'))
        )
    print(json.dumps({'contract': 'framac-eva-report-v1', 'exit_code': run.exit_code,
                      'complete': complete, 'has_assertion': has_assertion, 'properties': properties}))
    return run.exit_code


if __name__ == '__main__':
    raise SystemExit(main())
